### ISSUE TITLE
initial stream connect

### ISSUE THREAD

**Issue by adrpp** [ig-python/ig-markets-api-python-library#103]
Hello,

just wondering what creds needs to be passed into IG(Stream)Service cls.
Snippet taken from your sample code:
```
class config(object):
    username = "xxx"
    password = "xxx"
    api_key = "xxx"
    acc_type = "DEMO"  # LIVE / DEMO
    
from trading_ig import (IGService, IGStreamService)
ig_service = IGService(config.username, config.password, config.api_key, config.acc_type)
ig_stream_service = IGStreamService(ig_service)

ig_session = ig_stream_service.create_session()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/adrian/venv-ig/local/lib/python2.7/site-packages/trading_ig/stream.py", line 21, in create_session
    ig_session = self.ig_service.create_session()
  File "/home/adrian/venv-ig/local/lib/python2.7/site-packages/trading_ig/rest.py", line 944, in create_session
    response = self._req(action, endpoint, params, session)
  File "/home/adrian/venv-ig/local/lib/python2.7/site-packages/trading_ig/rest.py", line 204, in _req
    response = self.crud_session.req(action, endpoint, params, session)
  File "/home/adrian/venv-ig/local/lib/python2.7/site-packages/trading_ig/rest.py", line 121, in req
    return d_actions[action](endpoint, params, session)
  File "/home/adrian/venv-ig/local/lib/python2.7/site-packages/trading_ig/rest.py", line 72, in _create_first
    self._set_headers(response.headers, True)
  File "/home/adrian/venv-ig/local/lib/python2.7/site-packages/trading_ig/rest.py", line 126, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
  File "/home/adrian/venv-ig/local/lib/python2.7/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'cst'
```

I get 401 with '{"errorCode":"error.security.invalid-details"}'.
Username, password and api_key on config cls are set equaly to my IG account creds.

Thanks,
Adrian

**Comment by adrpp** [comment]
Solved, for those who run into same issue, use username and password from here:
IG Account -> Settings -> Demo|Live Accounts -> Web API demo login details 
instead of your IG account creds.
In other words, username and password needs to be created within MyIG account in order to be able to use it :)
