### ISSUE TITLE
TypeError: sequence item 1: expected str instance, bytes found

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#12]
When run sample/main.py

Sometimes, it raises the following exception

```
$ python sample/main.py
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): demo-api.ig.com
INFO:ig_stream:Starting connection with https://demo-apd.marketdatasystems.com
ERROR:ig_stream:Unable to connect to Lightstreamer Server
ERROR:ig_stream:Traceback (most recent call last):
  File "/Users/femto/github/ig-python/ig-markets-stream-api-python-library/trading_ig_stream/ig_stream.py", line 38, in connect
    self.ls_client.connect()
  File "/Users/femto/github/ig-python/ig-markets-stream-api-python-library/trading_ig_stream/lightstreamer/__init__.py", line 206, in connect
    logger.error("Server response error: \n%s" % "".join(lines))
TypeError: sequence item 1: expected str instance, bytes found
```

running again "fix" this problem

**Comment by bug-or-feature** [comment]
Very old issue. Proposing to close unless any objections....
