### ISSUE TITLE
from trading_ig import IGService

### ISSUE THREAD

**Issue by cyiannaki** [ig-python/ig-markets-api-python-library#128]
Hi,

I get the following message when I try to run: from trading_ig import IGService

Traceback (most recent call last):

  File "<ipython-input-1-c7cb8e889326>", line 1, in <module>
    from trading_ig import IGService

  File "/home/charlie/anaconda3/lib/python3.7/site-packages/trading_ig/__init__.py", line 17, in <module>
    from .rest import IGService

  File "/home/charlie/anaconda3/lib/python3.7/site-packages/trading_ig/rest.py", line 15, in <module>
    from .utils import (_HAS_PANDAS, _HAS_BUNCH)

  File "/home/charlie/anaconda3/lib/python3.7/site-packages/trading_ig/utils.py", line 21, in <module>
    from infi.bunch import bunchify

  File "/home/charlie/anaconda3/lib/python3.7/site-packages/infi/bunch/__init__.py", line 31, in <module>
    from .python3_compat import *

  File "/home/charlie/anaconda3/lib/python3.7/site-packages/infi/bunch/python3_compat.py", line 20, in <module>
    iteritems = dict.iteritems

AttributeError: type object 'dict' has no attribute 'iteritems'

Any help would be much appreciated.

Thanks,

Charlie

**Comment by cyiannaki** [comment]
Found the issue, it was with the file python3_compat.py

The code failed to detect that I was using Python 3+

**Comment by lewisb11** [comment]
How did you fix this though?

**Comment by cyiannaki** [comment]
Sorry don't have the code any more. It was a workaround and not a fix since I was using python 3. and the check within python3_compat.py returned the wrong version of python. I can't remember if this was caused by having both python 2. and 3. installed or just not using a venv.
