### ISSUE TITLE
I got a KeyError: 'cst' when I want to connect with the API

### ISSUE THREAD

**Issue by CallMeNachos** [ig-python/ig-markets-api-python-library#129]
I'm a new user of this API.
I followed the README.md but I couldn't figure the error out.

```from trading_ig import IGService
from trading_ig.config import config
ig_service = IGService(config.username, config.password, config.api_key, config.acc_type)
ig_service.create_session()

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/antoinefalieres/PycharmProjects/IG_Market/lib/python3.7/site-packages/trading_ig/rest.py", line 944, in create_session
    response = self._req(action, endpoint, params, session)
  File "/Users/antoinefalieres/PycharmProjects/IG_Market/lib/python3.7/site-packages/trading_ig/rest.py", line 204, in _req
    response = self.crud_session.req(action, endpoint, params, session)
  File "/Users/antoinefalieres/PycharmProjects/IG_Market/lib/python3.7/site-packages/trading_ig/rest.py", line 121, in req
    return d_actions[action](endpoint, params, session)
  File "/Users/antoinefalieres/PycharmProjects/IG_Market/lib/python3.7/site-packages/trading_ig/rest.py", line 72, in _create_first
    self._set_headers(response.headers, True)
  File "/Users/antoinefalieres/PycharmProjects/IG_Market/lib/python3.7/site-packages/trading_ig/rest.py", line 126, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
  File "/Users/antoinefalieres/PycharmProjects/IG_Market/lib/python3.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'cst'
```

**Comment by CallMeNachos** [comment]
@RRMXkun Do you have any ideas about that error ? pls

**Comment by RRMXkun** [comment]
Can you please check that your API key is correct in the config file? It looks like the server isn't returning a session token, which it should. Also check account type, username and password.

**Comment by bug-or-feature** [comment]
@CallMeNachos are you still experiencing the problem? Any credentials problems now show the IG error code

**Comment by bug-or-feature** [comment]
No response, closing
