### ISSUE TITLE
Error deploying to Kubernetes

### ISSUE THREAD

**Issue by alhennessey92** [ig-python/ig-markets-api-python-library#134]
I am getting the following error when trying to deploy one of my containers using this api to Kubernetes on GKE

```
Traceback (most recent call last):
[server]   File "app.py", line 7, in <module>
[server]     from trading_ig import IGService, IGStreamService
[server]   File "/usr/local/lib/python3.8/site-packages/trading_ig/__init__.py", line 17, in <module>
[server]     from .rest import IGService
[server]   File "/usr/local/lib/python3.8/site-packages/trading_ig/rest.py", line 15, in <module>
[server]     from .utils import (_HAS_PANDAS, _HAS_BUNCH)
[server]   File "/usr/local/lib/python3.8/site-packages/trading_ig/utils.py", line 21, in <module>
[server]     from infi.bunch import bunchify
[server]   File "/usr/local/lib/python3.8/site-packages/infi/bunch/__init__.py", line 31, in <module>
[server]     from .python3_compat import *
[server]   File "/usr/local/lib/python3.8/site-packages/infi/bunch/python3_compat.py", line 20, in <module>
[server]     iteritems = dict.iteritems
[server] AttributeError: type object 'dict' has no attribute 'iteritems'
```

I am guessing this is an error with using python3 over python2 but not sure.

**Comment by Filco306** [comment]
I get the same issue. Strange, because it works in a virtual environment with the exact same package versions installed.

**Comment by Filco306** [comment]
Did you manage to solve this? @alhennessey92

**Comment by Filco306** [comment]
I just solved it. To fix: 

1. Remove the `trading-ig`-line from your `requirement.txt`.
2. In your `Dockerfile`, add, below `RUN pip3 install -r requirements.txt`, add `RUN pip3 install git+https://github.com/ig-python/ig-markets-api-python-library`

This fixed it for me. With that, you are downloading the most recent version. You can also probably solve it by doing `RUN pip3 install pandas --force-reinstall`, which gives you a stable version instead.

**Comment by Filco306** [comment]
@alhennessey92 did you manage to run it inside a docker container? Please do let me know in that case.

**Comment by bug-or-feature** [comment]
Closing - no activity
