### ISSUE TITLE
KeyError: '_method' when deleting session headers

### ISSUE THREAD

**Issue by zansibal** [ig-python/ig-markets-api-python-library#238]
When upgrading from 0.0.9 to 0.0.15, I have found two _occasional_ exceptions. They happen to me (LIVE) now and then, on what seems to be depending on the response from IG.

The first one is addressed in this PR: https://github.com/ig-python/ig-markets-api-python-library/pull/237

The second one is the exception `KeyError: '_method'` after closing a position:
```
ERROR Unknown exception closing position (continuing): '_method'
Traceback (most recent call last):
  File "/home/ec2-user/.local/share/virtualenvs/indefatigable-Yel0zGn3/lib/python3.8/site-packages/trading_ig/rest.py", line 808, in close_open_position
    response = self._req(action, endpoint, params, session, version)
  File "/home/ec2-user/.local/share/virtualenvs/indefatigable-Yel0zGn3/lib/python3.8/site-packages/trading_ig/rest.py", line 204, in _req
    result = self._request(action, endpoint, params, session, version, check)
  File "/home/ec2-user/.local/share/virtualenvs/indefatigable-Yel0zGn3/lib/python3.8/site-packages/trading_ig/rest.py", line 213, in _request
    response = self.crud_session.req(action, endpoint, params, session, version)
  File "/home/ec2-user/.local/share/virtualenvs/indefatigable-Yel0zGn3/lib/python3.8/site-packages/trading_ig/rest.py", line 129, in req
    return d_actions[action](endpoint, params, session, version)
  File "/home/ec2-user/.local/share/virtualenvs/indefatigable-Yel0zGn3/lib/python3.8/site-packages/trading_ig/rest.py", line 118, in delete
    del session.headers['_method']
  File "/home/ec2-user/.local/share/virtualenvs/indefatigable-Yel0zGn3/lib/python3.8/site-packages/requests/structures.py", line 57, in __delitem__
    del self._store[key.lower()]
KeyError: '_method'
```

Again, these do not happen every time a position is closed. Only maybe every tenth time.

The POST action is ok:
`INFO DELETE (POST) '/positions/otc', resp 200`

**Comment by bug-or-feature** [comment]
@zansibal thanks for raising this. The '_method' thing seems to be some kind of hack to create a DELETE request by using a POST. I'm curious why we need to do that when there is a delete() function on the session object. I have a very vague memory that using delete() didn't work, but I can't remember why. Leave with me I'll do some more digging

**Comment by bug-or-feature** [comment]
Hi @zansibal 

The IG API is inconsistent in how DELETEs are handled. For logging out, sending an actual HTTP DELETE request works fine, but for the other cases, like removing a working order, we need to send a POST with a special '_method' header.

As a workaround, the latest (0.0.16) code now checks for the presence of the _method header before trying to remove it. Hopefully this fixes your occasional error
