### ISSUE TITLE
Seems not to work with share dealing account (even if ok with spread betting)

### ISSUE THREAD

**Issue by terzim** [ig-python/ig-markets-api-python-library#29]
Hi, 

I am testing the API library with my two IG accounts. 

When I set my "SPREAD BETTING" account as default on the IG platform, I receive the right output:

`
>>> import os
>>> import sys
>>> from trading_ig import IGService
>>> from trading_ig.config import config
>>> ig_service = IGService(config.username, config.password, config.api_key, config.acc_type)
>>> ig_service.create_session()
{u'reroutingEnvironment': None, etc... etc... : u'https://apd.marketdatasystems.com'}
`

However, When I set my "SHARE DEALING" account as default on the IG platform, I receive an error as below:

 `
>>> import os
>>> import sys
>>> from trading_ig import IGService
>>> from trading_ig.config import config
>>> ig_service = IGService(config.username, config.password, config.api_key, config.acc_type)
>>> ig_service.create_session()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/trading_ig/rest.py", line 946, in create_session
  File "build/bdist.linux-x86_64/egg/trading_ig/rest.py", line 204, in _req
  File "build/bdist.linux-x86_64/egg/trading_ig/rest.py", line 121, in req
  File "build/bdist.linux-x86_64/egg/trading_ig/rest.py", line 72, in _create_first
  File "build/bdist.linux-x86_64/egg/trading_ig/rest.py", line 126, in _set_headers
  File "/home/massi/.local/lib/python2.7/site-packages/requests/structures.py", line 56, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'cst'
`

Any idea of what is triggering the issue?

**Comment by femtotrader** [comment]
I have only done test with spread betting account.
I suggest to git clone repository and try some print debuging in https://github.com/ig-python/ig-markets-api-python-library/blob/master/trading_ig/rest.py

**Comment by terzim** [comment]
I think you can close this issue. Just tried with the API companion of IG to initiate a session and this is the return message I have got: 

`
{
    "errorCode": "error.public-api.failure.stockbroking-not-supported"
}
`

Seems the SHARE DEALING account is not supported by the API.

**Comment by femtotrader** [comment]
Thanks
