### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#5]
There is no Python 3 support for now

    $ python --version
    Python 3.4.3 :: Anaconda 2.3.0 (x86_64)

    $ python sample.py
    Traceback (most recent call last):
      File "sample.py", line 6, in <module>
        import igls,requests,json, time
      File "/Users/femto/ig-markets-stream-api-python-library/igls.py", line 425
        except urllib2.HTTPError, e:
                                ^
    SyntaxError: invalid syntax

**Comment by femtotrader** [comment]
see https://github.com/dw/py-lightstreamer/issues/1

**Comment by femtotrader** [comment]
see also https://github.com/Weswit/Lightstreamer-example-StockList-client-python/issues/2

**Comment by femtotrader** [comment]
Lightstreamer-example-StockList-client-python now have Python 3 support so it should help
