### ISSUE TITLE
crash if price enquiry returns no data(empty set) 

### ISSUE THREAD

**Issue by hklang10** [ig-python/ig-markets-api-python-library#61]
Currently, format_prices() is called unconditionally after the query is returned from the api.

This causes a traceback because the code cannot handle an empty set.  see #59 for example.

 I currently get:

```
epic = 'CS.D.EURUSD.MINI.IP'
resolution = '2H'
start_date = datetime.datetime(2017,9,11,9,0,0)
end_date = datetime.datetime(2017,9,11,9,1,0)
response = ig_service.fetch_historical_prices_by_epic_and_date_range(epic, resolution, start_date, end_date)
print (response)
```

```
Traceback (most recent call last):
  File "0-1.py", line 37, in <module>
    response = ig_service.fetch_historical_prices_by_epic_and_date_range(epic, resolution, start_date, end_date)
  File "/home/pi/projects/ig/igapi/trading_ig/rest.py", line 956, in fetch_historical_prices_by_epic_and_date_range
    data['prices'] = self.format_prices(data['prices'])
  File "/home/pi/projects/ig/igapi/trading_ig/rest.py", line 830, in format_prices
    last = prices[0]['lastTradedVolume'] \
IndexError: list index out of range
```

the IG api gives:

```
HTTP 200

status: success


cache-control: no-cache, no-store, must-revalidate
content-type: application/json
expires: 0
pragma: no-cache

{
    **"prices": [],**
    "instrumentType": "CURRENCIES",
    "metadata": {
        "allowance": {
            "remainingAllowance": 9995,
            "totalAllowance": 10000,
            "allowanceExpiry": 604061
        },
        "size": 0,
        "pageData": {
            "pageSize": 0,
            "pageNumber": 1,
            "totalPages": 0
        }
    }
}
```

**Comment by hklang10** [comment]
**list index out of range** is obviously not helpful.

The fix is simple, but how to fix?
a) traceback with a more meaningful "empty data set" exception ?
b) allow the program to continue normally, but with data['prices'] as an empty variable?
c) continue normally as b) but also log an information message ?

a) keeps the api behaviour the same, but gives a better traceback.
b) is the same behaviour as the IG api ( 200 status code, and prices is [] )
c) gives a console warning also as b)

How should the empty set be handled ?

**Comment by femtotrader** [comment]
I would choose a) also here
