### ISSUE TITLE
502 bad gateway is not detected

### ISSUE THREAD

**Issue by hklang10** [ig-python/ig-markets-api-python-library#65]
The server can issue 502 bad gateway at random.
I see this a lot after the close of business on Friday.
Re-trying the same code continually will sometimes respond OK, sometimes 502.

Currently the module will fail downstream with some random pandas fault or subscript out of range where the actual fault was a not OK response.

I will create a patch to explicitly handle responses which are not OK and to report their actual status codes.

**Comment by hklang10** [comment]
example of failure traceback (real reason is 502 status code)
Traceback (most recent call last):
  File "0-1.py", line 49, in <module>
```
    response = ig_service.search_markets(partial_epic)
  File "/home/pi/projects/ig/igapi/trading_ig/rest.py", line 777, in search_markets
    data = self.parse_response(response.text)
  File "/home/pi/projects/ig/igapi/trading_ig/rest.py", line 234, in parse_response_with_exception
    response = json.loads(*args, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by bug-or-feature** [comment]
Hi @hklang10 are you still seeing this issue? Did you create a patch? I can't see anything in git log

**Comment by bug-or-feature** [comment]
Closing - no activity
