### ISSUE TITLE
RemoteDisconnected after REST API call

### ISSUE THREAD

**Issue by hajderr** [ig-python/ig-markets-api-python-library#71]
Doing a REST API call as part of my app flow. The app has a stream subscription too. I get an error saying the remote end closed connection without response. This could happen after a  random amount of time, in this case the app had been running for about 10hours.

I'd prefer to avoid any manual monitoring of this and restart the app, right now I don't understand the root cause of this behaviour. Is IG shutting one off after a X amount of REST API calls? I'd approximate that the app is doing 1-2 REST API calls per minute. If I'd hit any limit, I'd expect an error code and message (as it's documented). 

```
Traceback (most recent call last):
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 307, in <module>
    main()
 **.........app code to fetch open position............**
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/trading_ig-0.0.6-py3.5.egg/trading_ig/rest.py", line 430, in fetch_open_positions
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/trading_ig-0.0.6-py3.5.egg/trading_ig/rest.py", line 218, in _req
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/trading_ig-0.0.6-py3.5.egg/trading_ig/rest.py", line 133, in req
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/trading_ig-0.0.6-py3.5.egg/trading_ig/rest.py", line 104, in read
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/linaro/IGT/venv/igt/lib/python3.5/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by hajderr** [comment]
No one with this problem? :)

**Comment by RRMXkun** [comment]
Since the error comes from such low level library as File "/usr/lib/python3.5/http/client.py", line 266, in _read_status

it is IG's server closing the connection, for unknown reasons, Nothing to do with the ig-markets library

**Comment by shrikantpadhy18** [comment]
How to resolve this error? any idea, I am facing the same.

**Comment by shrikantpadhy18** [comment]
> Since the error comes from such low level library as File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
> 
> it is IG's server closing the connection, for unknown reasons, Nothing to do with the ig-markets library

I am also facing the same error, please help
