### ISSUE TITLE
error.public-api.failure.encryption.required

### ISSUE THREAD

**Issue by kwtneo** [ig-python/ig-markets-api-python-library#82]
Hi, in following the examples:

```python
from trading_ig import IGService
from trading_ig_config import Config as config

ig_service = IGService(config.username, config.password, config.api_key, config.acc_type)
print(ig_service)
ig_service.create_session()
```
i'm getting the following error:

```python
Traceback (most recent call last):
  File "C:/Users/kwtne_000/PycharmProjects/dtr2/data_ig.py", line 6, in <module>
    ig_service.create_session()
  File "C:\Python27\lib\site-packages\trading_ig\rest.py", line 945, in create_session
    response = self._req(action, endpoint, params, session)
  File "C:\Python27\lib\site-packages\trading_ig\rest.py", line 205, in _req
    response = self.crud_session.req(action, endpoint, params, session)
  File "C:\Python27\lib\site-packages\trading_ig\rest.py", line 121, in req
    return d_actions[action](endpoint, params, session)
  File "C:\Python27\lib\site-packages\trading_ig\rest.py", line 72, in _create_first
    self._set_headers(response.headers, True)
  File "C:\Python27\lib\site-packages\trading_ig\rest.py", line 127, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
  File "C:\Python27\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'cst'
```
And when i include and if statement in rest.py that checks for 'CST',
like so:

```
            if 'CST' in response_headers:
                self.CLIENT_TOKEN = response_headers['CST']
```
My error changes to:
```
Traceback (most recent call last):
  File "C:/Users/kwtne_000/PycharmProjects/dtr2/data_ig.py", line 6, in <module>
    ig_service.create_session()
  File "C:\Python27\lib\site-packages\trading_ig\rest.py", line 946, in create_session
    data = self.parse_response(response.text)
  File "C:\Python27\lib\site-packages\trading_ig\rest.py", line 223, in parse_response_with_exception
    raise(Exception(response['errorCode']))
Exception: error.public-api.failure.encryption.required
```

any idea what i'm doing wrong?
credentials are working in the companion app.

**Comment by femtotrader** [comment]
I wonder if that's not an issue between CST (uppercased) and cst (lowercased)

**Comment by kwtneo** [comment]
i tried both - same error for api encryption failure.

**Comment by raphaelpierre** [comment]
Same error for me :( 
Any solution?

**Comment by TriEyeMonster** [comment]
encountered same issue, please help to fix it

**Comment by doggyeh** [comment]
I created a PR #100 to address this issue. It's required to encrypt the password during login for an account in some countries.
