### ISSUE TITLE
Lightstreamer SYNC ERROR

### ISSUE THREAD

**Issue by TraderVK** [ig-python/ig-markets-api-python-library#84]
Hello,

I randomly get the following error:

```
Server response error: 
SYNC ERROR
Exception in thread STREAM-CONN-THREAD-1:
Traceback (most recent call last):
  File "C:\Python36-32\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36-32\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python36-32\lib\site-packages\trading_ig-0.0.6-py3.6.egg\trading_ig\lightstreamer.py", line 386, in _receive
    self.bind()
  File "C:\Python36-32\lib\site-packages\trading_ig-0.0.6-py3.6.egg\trading_ig\lightstreamer.py", line 210, in bind
    self._handle_stream(stream_line)
  File "C:\Python36-32\lib\site-packages\trading_ig-0.0.6-py3.6.egg\trading_ig\lightstreamer.py", line 238, in _handle_stream
    raise IOError()
OSError
```

Maybe we could add `rebind = True` in lightstreamer.py as for the "LOOP ERROR" ?

**Comment by MohammadMoradi** [comment]
Hi, did you manage to solve the problem. I have exactly the same issue. Searching the net i found that rebind is required after this error. The root of problem is that you've subscribed too many items. As I reduced the number of subscribed items the error is gone. But how should I rebind to server?

**Comment by sacharbit** [comment]
Hi,
@TraderVK or @MohammadMoradi did you manage to solve the problem? I have the same issue :)
Thanks

**Comment by oliverpolden** [comment]
This is really odd. Looking at the latest code, rebind is set to True: https://github.com/ig-python/ig-markets-api-python-library/blob/master/trading_ig/lightstreamer.py#L352
But lower down there is an if statement `if not rebind:` which it runs as if rebind==False. i.e. it doesn't call self.bind()
So the code "looks" right but it's not running as expected. I'm fairly new to Python so can anyone understand why it's running the code in the `if not rebind:` block instead of in the `else` ?

**Comment by oliverpolden** [comment]
I've just stepped through the code locally and it got to the `else` block as expected. I then got the error above. Not sure if that's a result of running the debugger. I'm also confused as to why my server seems to be behaving differently. I ran the debugger again and I can now see it's got a LOOP and successfully rebinded and carried on.
