### ISSUE TITLE
Not working ig_service.fetch_historical_prices_by_epic_and_date_range : KeyError: 'lastTraded'

### ISSUE THREAD

**Issue by kiann00** [ig-python/ig-markets-api-python-library#89]
I am trying to load up the historical prices using the example. I am getting an error message as per below.

Code as below ```
from datetime import datetime, timedelta
start_date = datetime.now() - timedelta(hours=39)
end_date = datetime.now() - timedelta(hours = 38)
response = ig_service.fetch_historical_prices_by_epic_and_date_range('CS.D.EURUSD.CFD.IP', '1Min', start_date, end_date, ig_session)
```

Error message
---------------
Traceback (most recent call last):

  File "<ipython-input-1-40eaee59765c>", line 46, in <module>
    response = ig_service.fetch_historical_prices_by_epic_and_date_range('CS.D.EURUSD.CFD.IP', '1Min', start_date, end_date, ig_session)

  File "C:\ProgramData\Anaconda3\lib\site-packages\trading_ig\rest.py", line 836, in fetch_historical_prices_by_epic_and_date_range
    data['prices'] = self.format_prices(data['prices'])

  File "C:\ProgramData\Anaconda3\lib\site-packages\trading_ig\rest.py", line 750, in format_prices
    df = json_normalize(prices)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\json\normalize.py", line 203, in json_normalize
    data = nested_to_record(data, sep=sep)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\json\normalize.py", line 88, in nested_to_record
    new_d.update(nested_to_record(v, newkey, sep, level + 1))

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\json\normalize.py", line 84, in nested_to_record
    new_d.pop(k)

KeyError: 'lastTraded'

---------------------

**Comment by firebird631** [comment]
Try with MINUTE and not 1Min

**Comment by RRMXkun** [comment]
1Min is correct since in utils.py there is some sort of translation:

```
d = {
            to_offset('1Min'): 'MINUTE',
            to_offset('2Min'): 'MINUTE_2',
            to_offset('3Min'): 'MINUTE_3',
            to_offset('5Min'): 'MINUTE_5',
            to_offset('10Min'): 'MINUTE_10',
            to_offset('15Min'): 'MINUTE_15',
            to_offset('30Min'): 'MINUTE_30',
            to_offset('1H'): 'HOUR',
            to_offset('2H'): 'HOUR_2',
            to_offset('3H'): 'HOUR_3',
            to_offset('4H'): 'HOUR_4',
            to_offset('D'): 'DAY',
            to_offset('W'): 'WEEK',
            to_offset('M'): 'MONTH'
        }
```

Not sure what the reason is, doesn't seem to change a whole lot.

@kiann00 
I was able to run your code just fine (although that epic doesn't exist for me so I used CS.D.BITCOIN.CFP.IP), are you sure you are using the latest version of the source files?

**Comment by MallikarjunTirlapur** [comment]
Is this issue resolved? I am facing with this issue. Can you please help me?

 response = ig_service.fetch_historical_prices_by_epic_and_date_range(epic, resolution, start_date, end_date, session)

  File "C:\Users\sramy\Anaconda3\lib\site-packages\trading_ig\rest.py", line 988, in fetch_historical_prices_by_epic_and_date_range
    data['prices'] = self.format_prices(data['prices'], version)

  File "C:\Users\sramy\Anaconda3\lib\site-packages\trading_ig\rest.py", line 855, in format_prices
    df = json_normalize(prices)

  File "C:\Users\sramy\Anaconda3\lib\site-packages\pandas\io\json\normalize.py", line 203, in json_normalize
    data = nested_to_record(data, sep=sep)

  File "C:\Users\sramy\Anaconda3\lib\site-packages\pandas\io\json\normalize.py", line 88, in nested_to_record
    new_d.update(nested_to_record(v, newkey, sep, level + 1))

  File "C:\Users\sramy\Anaconda3\lib\site-packages\pandas\io\json\normalize.py", line 84, in nested_to_record
    new_d.pop(k)

KeyError: 'lastTraded'

**Comment by firebird631** [comment]
It seems your issue is in the panda conversion part. In my case I have removed all pandas references of this library. In a first time try to look what it return to you without pandas.

**Comment by MallikarjunTirlapur** [comment]
Thank you very much for your replay. How do you remove pandas reference from the lib? You replace pandas with some other library?

**Comment by firebird631** [comment]
The simplest is in utils.py _HAS_PANDAS = True to _HAS_PANDAS = False. The other solution, you remove all part having _HAS_PANDAS in rest.py.

**Comment by bug-or-feature** [comment]
Closing, resolved
